### ISSUE TITLE
Problems while trying to execute release-em on windows

### ISSUE THREAD

**Issue by Disane87** [danderson00/release-em#2]
Firt at all, thank you for this awesome project! I want to use it cause I have a multiproject angular project with many libraries to publish (one by one or just a bunch of them).

I installed it globally and locally with npm (just for testing purposes, but I prefer to have it locally in my project). But if I want to execute it with `release-em` windows is just sayin' 

> Der Befehl ""C:\Users\mfranke\AppData\Roaming\npm\\node_modules\release-em\bin"" ist entweder falsch geschrieben oder konnte nicht gefunden werden

Actually it can't find the command for the executable. My system: Windows 10 x64.

This happens with release-em installed globally and locally.

The global folder is existend:
![image](https://user-images.githubusercontent.com/956158/62925666-20499680-bdb3-11e9-9d94-69a24a60af28.png)

But I think there is no suited executable in the `bin` folder:
![image](https://user-images.githubusercontent.com/956158/62925681-293a6800-bdb3-11e9-9e76-2d5c43f76e0b.png)

**Comment by danderson00** [comment]
Apologies for the lack of response! For some reason my github notification settings are all messed up.

I'm pretty sure this is due to the `bin` setting in `package.json` not being set correctly. I'll have a look at it this afternoon and publish a new package.

**Comment by danderson00** [comment]
This is fixed. Thanks for opening an issue!

Again, apologies for the delay in responding. I've fixed my notification problem now! If you have any other issues, please don't hesitate to open new issues.

**Comment by Disane87** [comment]
> This is fixed. Thanks for opening an issue!
> 
> Again, apologies for the delay in responding. I've fixed my notification problem now! If you have any other issues, please don't hesitate to open new issues.

No problem :) will test it when I have some spare time between the xmas days.
