### ISSUE TITLE
Syncing dependency versions with breaking changes

### ISSUE THREAD

**Issue by Techn1x** [danderson00/release-em#4]
We're looking at this project as an alternative to our Lerna workflow. We currently use Lerna + Yarn workspaces to manage our monorepo, changelog and package versioning (using conventional commits).

Thinking we would be using Release 'Em! + release-it/conventional-changelog plugin, are there any potential gotcha's I might not have considered yet?

Our current issues with Lerna are;
* if a package publishes a breaking change (indicated by conventional commit), Lerna will still automatically bump other packages using that package dependency. We'd like to have some say over this behaviour
* recovering from a failed publish is problematic, due to git tags being pushed to github before attempting an npm publish - if the publish fails, we need to delete git tags from the remote, which is risky

How does Release Em handle syncing dependency versions when breaking changes are involved? Is there any way to configure this behaviour? (either via config, or via prompts)

Looking at Release It, it seems to allow for skipping steps of the release process with flags like --no-git.tag or --no-git, this should help when recovering from a failed publish. Is it possible to pass these flags to Release It when using Release Em? What kind of state can a package be left in when a partially completed or failed publish occurs? Or does the use of `--validate` make this a complete non-issue?

**Comment by danderson00** [comment]
release-em is intended to provide some additional level of protection against failed publishing. For example, there's an extra check for `accessConfig` attributes in `package.json` for scoped packages. The `--validate` option does indeed run these checks before doing any publishing, and runs `npm publish --dry-run` for each package. 

Having said this, there are some scenarios I'm aware of that the dry run doesn't pick up, like attempting to publish over an existing version. There is an [issue open](https://npm.community/t/publish-dry-run-result-in-a-failure-if-version-already-published/5221) on the npm site, but given the length of time it's been open, it doesn't look like it will be fixed any time soon. At some point, we'll implement an internal check for these sorts of things - a single package publish failing mid way through publishing a bunch of packages is a pain!

Currently, recovering from a failed publish is done by re-running release-em manually as appropriate.  This is far from ideal, but the goal is to build enough pre-checks to make it a rarity. We could also build some specific recovery functionality, but I haven't looked at this yet.

As far as breaking changes are concerned, release-em will only bump versions and publish the packages specified on the command line, but will update the versions of published packages in the `package.json` of all packages in the workspace. There isn't any way to control this at the moment, but it would be fairly simple to provide some control.

I haven't been using release-em recently and am aware of some reliablity issues, but need to spend some time soon, so these issues should be fixed soon, along with some of the pre-checks mentioned above. If you find any problems, raise an issue here and I should be able to fix it reasonably quickly, and the feedback would be much appreciated!
